### ISSUE TITLE
buffer-crypto's instrumented suite hangs on CI's emulator — and has never run there

### ISSUE THREAD

**Issue by thebehera** [DitchOoM/buffer#344]
Two coupled problems, found while adding `:buffer-crypto` to `androidConnectedTests` in #343. The addition was reverted from that PR so the X25519 fix could land; this is the finding it surfaced.

## 1. `buffer-crypto` has never run on an emulator in CI

`androidConnectedTests` (root `build.gradle.kts`) lists `:buffer-compression`, `:buffer-flow` and `:buffer-codec` — not `:buffer-crypto`. So neither emulator leg has ever executed it.

That is the module where it matters most. buffer-crypto is the one whose behaviour diverges most between JCA implementations — the JDK's providers on a host JVM versus **Conscrypt** on a device — and none of that divergence was ever exercised anywhere.

It is not hypothetical: #343 fixes a defect where X25519 was reported `Unavailable` on **every** Android API level (Conscrypt's `XDH` `KeyPairGenerator` refuses every `AlgorithmParameterSpec`, and its key does not implement `XECPublicKey`). That shipped because nothing ran on a device, and because `KeyAgreementTest` *skips* curves the target reports as unavailable — so its entire X25519 suite passed by never running.

The regression test added in #343 (`X25519CapabilityHonestyTest`) currently runs only on the JVM, where the bug cannot reproduce. **Its guard is dormant until this is resolved.**

## 2. It hangs when it does run

Adding it produced a 15-minute job timeout on the API-35 leg
([run](https://github.com/DitchOoM/buffer/actions/runs/31431986076/job/93597342143)):

```
21:08:12  > Task :buffer-crypto:connectedDebugAndroidTest
21:08:20  Starting 369 tests on emulator-5554 - 15
21:08:24  UserAuthBindingInstrumentedTest > sessionBoundAgreementIsRefusedByTheKeystoreWithoutAuthentication  SKIPPED
21:08:24  UserAuthBindingInstrumentedTest > sessionBoundKeyIsRefusedByTheKeystoreWithoutAuthentication        SKIPPED
21:08:25  UserAuthBindingInstrumentedTest > perUseKeyIsRefusedWhenTheCryptoObjectWasNeverAuthorized          SKIPPED
          ... no further output for 9.5 minutes ...
21:17:56  OK: killing emulator, bye bye
```

Silence rather than streaming results, so this is a hang and not slowness. The API-21 leg is unaffected — buffer-crypto is minSdk 28, so it skips cleanly there.

### It does not reproduce locally

The identical command completes in **42 seconds**, all four modules, 372 tests, same three SKIPPEDs:

```
./gradlew connectedAndroidTestCompatible -PdeviceApiLevel=35   # local AVD, API 35
```

So it is environment-dependent. Two differences worth starting from:

- **Module order.** Locally `buffer-crypto` ran **first**; in CI it ran **third**, after `buffer-flow` (14 tests) and `buffer-codec` (177) had already used the emulator. A wedged keystore daemon or exhausted emulator after prior modules would fit.
- **AVD state.** CI cold-boots a fresh `google_apis;x86_64` AVD with no lock screen, no keystore state, `-no-window`. The local AVD carries prior state, and (being an OOM-testing AVD) likely a different memory configuration — relevant given `ANDROID_ART_ALLOCATOR.md`.

Prime suspect is the `UserVerification` surface from #341: interactive biometric/credential checks are exactly what blocks forever on a headless emulator with no user to respond. The three tests that *did* report were `UserAuthBindingInstrumentedTest`, and the stall begins immediately after them. Unconfirmed — the hanging test is not named in the log, since the runner reports on completion.

## Suggested resolution

1. Identify the hanging test (a per-test timeout, or `-Pandroid.testInstrumentationRunnerArguments.class=...` bisection on a fresh AVD, would name it).
2. Skip or guard it on an emulator, the way `UserAuthBindingInstrumentedTest` already skips.
3. Re-add `Triple(":buffer-crypto", ":buffer-crypto:connectedDebugAndroidTest", 28)` to `androidConnectedTests`. Verified scheduling with `--dry-run` on both legs: API 35 schedules it, API 21 skips with a logged reason.
4. Raise `timeout-minutes` on the emulator job — 15 was already close before adding a fourth module.

Until (3), any Conscrypt-versus-JDK divergence in buffer-crypto remains unexercised by CI.

**Comment by thebehera** [comment]
## Root-caused, and it does reproduce locally — the variable is device *enrollment state*, not the environment

Reproduced on a local AVD while verifying the follow-up commit on #343. `:buffer-crypto:connectedDebugAndroidTest` on a fresh **API 36 arm64** AVD (`Test_API_36_ARM`, no screen lock, no fingerprint) hung for 10+ minutes, same silent shape as CI:

```
17:42:43.052 TestRunner: started:  deviceLockSetupRemedyReturnsHonestlyWhenLockNotSet(UserVerificationInstrumentedTest)
17:42:44.059 TestRunner: finished: deviceLockSetupRemedyReturnsHonestlyWhenLockNotSet(UserVerificationInstrumentedTest)
17:42:44.062 TestRunner: started:  enrollmentRemedyReturnsHonestlyWhenNotEnrolled(UserVerificationInstrumentedTest)
          ... no further output; still running at 17:52:53 ...
```

`dumpsys activity activities` at that point:

```
topResumedActivity=ActivityRecord{... com.android.settings/.password.ChooseLockGeneric ...}
```

So it is not slowness and not the emulator: **the suite launched a real OS Settings activity and is waiting for a human to finish it.** `deviceLockSetupRemedyReturnsHonestlyWhenLockNotSet` invoked `openDeviceLockSetup` and returned, leaving `ChooseLockGeneric` resumed in the foreground; `enrollmentRemedyReturnsHonestlyWhenNotEnrolled` then called `runBlocking { remedy() }` on `openEnrollment`, which never returns. Nobody dismisses the dialog on a headless runner.

### Why "does not reproduce locally" was misleading

Both tests early-return unless the device is in the matching state:

```kotlin
val notEnrolled = state.biometric as? BiometricAvailability.Actionable.NotEnrolled ?: return
val lockNotSet  = state.biometric as? BiometricAvailability.Actionable.DeviceLockNotSet ?: return
```

A device that already has a screen lock and a fingerprint enrolled — RMX3933, and most likely the API 35 AVD used for the 42-second run — never reaches the `remedy()` call, so nothing launches and nothing hangs. A **fresh** emulator, which is exactly what CI creates every run, takes the actionable branch and invokes the remedy for real. The trigger is enrollment state, not the runner.

That also explains the CI log ending after three `UserAuthBindingInstrumentedTest ... SKIPPED` lines: those skip for the same reason (no credential), and execution then reaches the tests that *don't* skip on a bare device.

### Consequence for part 1

Adding `:buffer-crypto` to `androidConnectedTests` cannot land until these two tests stop launching un-dismissable OS UI on an unattended device. Whatever the fix is (gate on `isUserAuthenticationSupported`-style state, assert the intent resolves rather than launching it, or mark them attended-only), the choice is between "assert the remedy resolves" and "assert the remedy launches" — only the first is safe on a headless runner.

### Not blocking #343

The X25519 fix and its regression test were verified on this same API 36 emulator by running the key-agreement classes directly:

```
run finished: 3 tests, 0 failed, 0 ignored   # X25519CapabilityHonestyTest
run finished: 12 tests, 0 failed, 0 ignored  # KeyAgreementTest
```

`X25519CapabilityHonestyTest` **is** in the instrumented APK (`androidInstrumentedTest dependsOn jvmCommonTest`) and passes against Conscrypt on device — so the guard works; it is only CI that never invokes it.
